name: MSVC-CI
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A Win32 ..
          cmake --build . --config Debug

      # This should probably be fixed to work from MSVC without needing to
      # use a bash shell and the GNU userland tools...  But for now, the
      # GH Actions environment provides what we need.
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Build
          path: build/debug/
